### ISSUE TITLE
Return statement inside the "for" loop

### ISSUE THREAD

**Issue by Pepslee** [up42/processing-block-template#2]
You have the return statement inside the "for" loop. In this way you will get only the first item from "process" method but never get a second.
[processing_block.py](https://github.com/up42/processing-block-template/blob/master/src/processing_block.py)

**Comment by rodrigoalmeida94** [comment]
@Pepslee sorry for the delay in responding - somehow we weren't monitoring these issues here! 

Thanks a lot for your note, just committed a fix.
